//
//	DO NOT EDIT THIS FILE
//	IT IS AUTO GENERATED BY MGC
//	TEMPLATE: gomod.template
//
// github.com/MagaluCloud/mgc-sdk-go v1.0.0

module github.com/magaluCloud/mgccli

go 1.25.3

require (
	github.com/MagaluCloud/mgc-sdk-go v1.0.0
	github.com/fatih/color v1.16.0
	github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c
	github.com/spf13/cobra v1.9.1
	github.com/spf13/pflag v1.0.6
)

require (
	github.com/golang-jwt/jwt/v5 v5.3.0
	github.com/inconshreveable/mousetrap v1.1.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	golang.org/x/sys v0.33.0 // indirect
	gopkg.in/yaml.v3 v3.0.1
)
